version: 3
workdir: .

allow:
  depOnAnyVendor: true
  deepScan: true

excludeFiles:
  - ".*_test\\.go$"

components:
  cmd:       { in: cmd/** }
  config:    { in: internal/config }
  domain:    { in: internal/image }
  avio:      { in: internal/avio }
  frame:     { in: internal/frame }
  metadata:  { in: internal/metadata }
  server:    { in: internal/server }
  source:    { in: internal/source/** }
  storage:   { in: internal/storage }
  version:   { in: internal/version }

commonComponents:
  - domain
  - avio
  - frame
  - metadata
  - source
  - version

deps:
  cmd:
    mayDependOn:
      - config
      - server
      - storage

  storage:
    mayDependOn:
      - config
